### ISSUE TITLE
FL010U location

### ISSUE THREAD

**Issue by trvrb** [andersen-lab/zika-florida#4]
FL010U should have its metadata location updated to `usa` from `usa_ex_cuba` here: 

https://github.com/andersen-lab/zika-florida/blob/master/consensus_sequences/FL010U%7CKX842449%7C2016-06-22%7Cusa_ex_cuba.fasta.gz

**Comment by kga1978** [comment]
Thanks. Updated.

**Comment by trvrb** [comment]
Thanks Kristian!
